;
; In the .ini file, values should be enclosed in double quotes (").
;
; Description of configuration parameters:
;
; [Globals]
;
; commonSeparators = "<list of single UTF8 characters>". Default: ",;\t|:~^"
;    This global is used to automatically determine what format to use for a given CSV file.
;
; commonEncloserPairs = "<list of single UTF8 characters>". Default: "\"'"
;    This global is used to automatically determine what format to use for a given CSV file.
;
; clickToSelectColumn = <true|1 or false|0>. Default: "true"
;    This enables or disables column selection when a cell value is clicked.
;
; NOTE: Automatic determination of the format to use for a given CSV file uses
;       the common separators and enclosers specified in this file. The first
;       few lines of the CSV file are parsed to see which separators and
;       enclosers appear most frequently.
;
;       Simply add to these lists if the CSV files use other characters as
;       separators and/or enclosers (e.g. Unicode symbols). This plugin
;       expects these lists to be a collection of single UTF8 characters.
;
; [Format Name] - Lines that look like this are names of the formats. A format is a collection of parameters specifying
;                 things like the separator (e.g. a comma), and the character that encloses a column value
;                 (e.g. a double quote), cell coordinates format, and the tooltip format.
;
;                 During parsing of the configuration file, new formats are created with the default configuration values
;                 (see below), and then any or all the default values can be overriden.
;
; separator = "<column separator>"
;    This parameter defines the character or string that separates values in rows. Default: ",".
;    Common separators: "," ";" "\t" "|" ":" "~" "^"
;
; encloseWith = "<column encloser>"
;    This parameter defines the single character or character pair that "wraps" the column value. Default "\"".
;    Common enclosers: "\"", "'"
;
; coordinatesFormat = <either "A1" or "R1C1">. Default: "A1".
;    This parameter defines how the cell coordinates will be shown in the tooltip/calltip.
;
;    "A1" means show the cell coordinates in the standard format for Libre Calc/Excel.
;
;    "R1C1" means show the coordinates with the row and column specified as numbers.
;    
; tooltipFormat = "<format string>". Default: "@Header (@Coordinates)".
;    This parameter defines how the tooltip/calltip will look when it pops up while hovering over a column.
;
;    @Header is replaced by the text from the column in the first row.
;
;    @Coordinates is replaces by the coordinates of the cell in the format chosen with coordinatesFormat.
;
; I18N NOTE:
;
; If the CSV file contains a mix of LTR and RTL cell values (e.g. mix of
; English and Arabic), generate the CSV file with cells having RTL content
; that are enclosed within 'encloseWith' characters so column highlighting
; works properly.
;
; See the "utf8.csv" example file.
;

;------------------------------------------------------------------------------------------------

[Globals]
commonSeparators = ",;\t|:~^"
commonEnclosers = "\"'"
clickToSelectColumn = "true"

;
; This is the default format configuration built into the plugin. Here for reference purposes only.
;
;[Comma]
;separator = ","
;encloseWith = "\""
;coordinatesFormat = "A1"
;tooltipFormat = "@Header (@Coordinates)"

;
; Example formats that have different separators, and one with a different separator and encloser from the default.
;
[Semicolon]
separator = ";"

[Tab]
separator = "\t"

[Carat]
separator = "^"
encloseWith = "'"

;
; Example configuration that specifies a vertical bar separator, no enclosing character around the column values,
; and a (row,column) coordinates displayed in the cell tooltips (when mouse pointer is hovering over a cell).
;
[Pipe]
separator="|"
encloseWith=""
coordinatesFormat="R1C1"

[Up Arrow]
separator="↑"
encloseWith="‘"
